# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            咬一口聖經
tagline:          以西結說，那滋味像蜂蜜般甘甜。
url:              http://sillyleo.github.io/OneBite/
paginate:         20
baseurl:          /
author:
  name:           Leo Lin
  url:            https://twitter.com/sillyleo
  email:          leolin@me.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
